### ISSUE TITLE
Timer

### ISSUE THREAD

**Issue by shuding** [chenglou/pure-css-shaders-art#1]
Wonderful project and now I can delete my WebGL template! However, timer is a missing piece here so I tried to include this:

```css
@property --t {
  syntax: '<number>';
  inherits: true;
  initial-value: 0;
}
@keyframes timer {
  from {
    --t: 0;
  }
  to {
    --t: 1;
  }
}
:root {
  animation: timer 10s infinite steps(300);
}
```

And it worked (`--atan-div: calc(var(--v) * var(--t) / (var(--u) + 0.001));`)! Should we have it in the predefined CSS? Sadly `@property` is not yet supported by all modern browsers though :D

<img src="https://user-images.githubusercontent.com/3676859/154802908-4bd42dbb-3ba0-468c-a916-7d006cc9cf16.gif" width="100" height="100" />
